import { Header } from '@/components/shared'
import type { Metadata } from 'next'
import React, { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface LayoutProps {
  children: ReactNode
  modal?: ReactNode
}
export default function HomeLayout({
  children,
  modal
}: LayoutProps) {


  return (
    <main className={'min-h-screen'}>
      <div>
        <Header />
        {children}
        {modal}
      </div>
    </main>
  )
}

export const dynamicParams = true

